CREATE TABLE IF NOT EXISTS invoice_contacts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(191) NOT NULL,
    department_name VARCHAR(191) NULL,
    contact_name VARCHAR(191) NULL,
    honorific VARCHAR(32) NULL,
    email VARCHAR(255) NULL,
    postal_code VARCHAR(32) NULL,
    address1 VARCHAR(255) NULL,
    address2 VARCHAR(255) NULL,
    phone VARCHAR(64) NULL,
    freee_partner_name VARCHAR(191) NULL,
    default_due_days INT NULL,
    note TEXT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX idx_invoice_contacts_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS invoice_headers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    invoice_no VARCHAR(32) NOT NULL,
    issue_date DATE NOT NULL,
    due_date DATE NOT NULL,
    contact_id INT NULL,
    contact_name_snapshot VARCHAR(191) NOT NULL,
    contact_department_snapshot VARCHAR(191) NULL,
    contact_person_snapshot VARCHAR(191) NULL,
    contact_honorific_snapshot VARCHAR(32) NULL,
    contact_email_snapshot VARCHAR(255) NULL,
    contact_postal_code_snapshot VARCHAR(32) NULL,
    contact_address1_snapshot VARCHAR(255) NULL,
    contact_address2_snapshot VARCHAR(255) NULL,
    contact_phone_snapshot VARCHAR(64) NULL,
    subject VARCHAR(255) NOT NULL,
    note TEXT NULL,
    bank_info TEXT NULL,
    issuer_name VARCHAR(191) NOT NULL,
    issuer_postal_code VARCHAR(32) NULL,
    issuer_address1 VARCHAR(255) NULL,
    issuer_address2 VARCHAR(255) NULL,
    issuer_phone VARCHAR(64) NULL,
    issuer_email VARCHAR(255) NULL,
    subtotal_yen INT NOT NULL DEFAULT 0,
    tax_yen INT NOT NULL DEFAULT 0,
    total_yen INT NOT NULL DEFAULT 0,
    tax_mode VARCHAR(16) NOT NULL DEFAULT 'external',
    status VARCHAR(16) NOT NULL DEFAULT 'draft',
    pdf_generated_at DATETIME NULL,
    pdf_storage_path VARCHAR(512) NULL,
    mailed_at DATETIME NULL,
    freee_exported_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE KEY uniq_invoice_headers_invoice_no (invoice_no),
    INDEX idx_invoice_headers_issue_date (issue_date),
    INDEX idx_invoice_headers_due_date (due_date),
    INDEX idx_invoice_headers_status (status),
    INDEX idx_invoice_headers_contact_name (contact_name_snapshot)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS invoice_items (
    id INT AUTO_INCREMENT PRIMARY KEY,
    invoice_id INT NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    item_name VARCHAR(255) NOT NULL,
    quantity DECIMAL(12,2) NOT NULL DEFAULT 1.00,
    unit_name VARCHAR(32) NULL,
    unit_price_yen INT NOT NULL DEFAULT 0,
    line_total_yen INT NOT NULL DEFAULT 0,
    tax_category VARCHAR(64) NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX idx_invoice_items_invoice_id (invoice_id),
    INDEX idx_invoice_items_sort_order (sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS invoice_issuer_templates (
    id INT AUTO_INCREMENT PRIMARY KEY,
    template_name VARCHAR(255) NOT NULL,
    issuer_name VARCHAR(191) NOT NULL,
    issuer_postal_code VARCHAR(32) NULL,
    issuer_address1 VARCHAR(255) NULL,
    issuer_address2 VARCHAR(255) NULL,
    issuer_phone VARCHAR(64) NULL,
    issuer_email VARCHAR(255) NULL,
    bank_info TEXT NULL,
    note TEXT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    is_default TINYINT(1) NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX idx_invoice_issuer_templates_sort_order (sort_order, id),
    INDEX idx_invoice_issuer_templates_is_default (is_default, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS invoice_mail_logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    invoice_id INT NOT NULL,
    to_email VARCHAR(512) NOT NULL,
    cc_email VARCHAR(512) NULL,
    bcc_email VARCHAR(512) NULL,
    subject VARCHAR(255) NOT NULL,
    body TEXT NULL,
    attachment_filename VARCHAR(255) NULL,
    sent_at DATETIME NULL,
    status VARCHAR(32) NOT NULL,
    error_message TEXT NULL,
    created_at DATETIME NOT NULL,
    INDEX idx_invoice_mail_logs_invoice_id (invoice_id),
    INDEX idx_invoice_mail_logs_sent_at (sent_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS invoice_csv_logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    invoice_id INT NOT NULL,
    filename VARCHAR(255) NOT NULL,
    exported_at DATETIME NOT NULL,
    status VARCHAR(32) NOT NULL,
    error_message TEXT NULL,
    created_at DATETIME NOT NULL,
    INDEX idx_invoice_csv_logs_invoice_id (invoice_id),
    INDEX idx_invoice_csv_logs_exported_at (exported_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
