[mfu-sensitive-probe]
enabled = true
filter = mfu-sensitive-probe
logpath = /var/log/apache2/mfu_access.log
backend = auto
port = http,https
maxretry = 2
findtime = 60
bantime = 3600
bantime.increment = true
bantime.factor = 24
bantime.maxtime = 86400

