#!/usr/bin/env bash
set -euo pipefail

stamp=$(date +%Y%m%d%H%M%S)
cp -a /etc/asterisk/extensions_custom.conf "/etc/asterisk/extensions_custom.conf.bak.${stamp}"
cp -a /usr/local/sbin/mfu-whitelist-gateway "/usr/local/sbin/mfu-whitelist-gateway.bak.${stamp}"
cp -a /etc/sudoers.d/mfu-whitelist "/etc/sudoers.d/mfu-whitelist.bak.${stamp}"

install -o root -g root -m 0755 /tmp/mfu-call-through /usr/local/sbin/mfu-call-through
install -o root -g root -m 0755 /tmp/mfu-whitelist-gateway /usr/local/sbin/mfu-whitelist-gateway
install -o root -g root -m 0440 /tmp/mfu-whitelist.sudoers /etc/sudoers.d/mfu-whitelist
install -o root -g root -m 0440 /tmp/mfu-call-through.sudoers /etc/sudoers.d/mfu-call-through
install -o root -g asterisk -m 0640 /tmp/mfu_call_through.conf /etc/asterisk/mfu_call_through.conf

if [[ ! -e /etc/asterisk/mfu_call_through_generated.conf ]]; then
  install -o root -g asterisk -m 0640 /dev/null /etc/asterisk/mfu_call_through_generated.conf
  printf '; Generated by mfu-call-through. Do not edit.\n[mfu-call-through-reservation]\n' \
    > /etc/asterisk/mfu_call_through_generated.conf
  chown root:asterisk /etc/asterisk/mfu_call_through_generated.conf
  chmod 0640 /etc/asterisk/mfu_call_through_generated.conf
fi

if ! grep -Fq 'U(mfu-call-through-answered^${MFU_CT_RESERVATION_ID})' /etc/asterisk/extensions_custom.conf; then
  sed -i \
    '/U(mfu-click-to-call-answered/a\ same => n,ExecIf($["${MFU_CT_RESERVATION_ID}"!=""]?Set(DIAL_TRUNK_OPTIONS=${DIAL_TRUNK_OPTIONS}U(mfu-call-through-answered^${MFU_CT_RESERVATION_ID})))' \
    /etc/asterisk/extensions_custom.conf
fi

if ! grep -Fq 'mfu-call-through-reservation,${NORMALIZED_CID}' /etc/asterisk/extensions_custom.conf; then
  sed -i \
    '/DIALPLAN_EXISTS(callerid-blacklist-entries,${NORMALIZED_CID}/a\ same => n,Set(MFU_CT_RESERVATION_ID=)\n same => n,GosubIf($["${DIALPLAN_EXISTS(mfu-call-through-reservation,${NORMALIZED_CID},1)}" = "1"]?mfu-call-through-reservation,${NORMALIZED_CID},1)\n same => n,Set(MFU_CT_CURRENT_DID=${FILTER(0-9,${FROM_DID})})\n same => n,ExecIf($["${MFU_CT_CURRENT_DID}" = ""]?Set(MFU_CT_CURRENT_DID=${FILTER(0-9,${CDR(did)})}))\n same => n,GotoIf($["${MFU_CT_RESERVATION_ID}" != "" & ${EPOCH} < ${MFU_CT_EXPIRES_AT} & "${MFU_CT_CURRENT_DID}" = "${MFU_CT_INBOUND_DID}"]?call-through)' \
    /etc/asterisk/extensions_custom.conf
  sed -i \
    '/same => n(allowed),NoOp/i\ same => n(call-through),Goto(custom-mfu-call-through,s,1)' \
    /etc/asterisk/extensions_custom.conf
fi

if ! grep -Fxq '#include mfu_call_through.conf' /etc/asterisk/extensions_custom.conf; then
  printf '\n#include mfu_call_through.conf\n' >> /etc/asterisk/extensions_custom.conf
fi

/usr/bin/python3 -m py_compile /usr/local/sbin/mfu-call-through
/bin/bash -n /usr/local/sbin/mfu-whitelist-gateway
/usr/sbin/visudo -cf /etc/sudoers.d/mfu-whitelist
/usr/sbin/visudo -cf /etc/sudoers.d/mfu-call-through
/usr/sbin/asterisk -rx 'dialplan reload'
